CREATE DATABASE IF NOT EXISTS guestbook;
-- DROP DATABASE IF EXISTS guestbook;


CREATE TABLE IF NOT EXISTS  `guestbook`.`guestbook` (
  `guestNum` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guestTitle` VARCHAR(50) NULL DEFAULT NULL,
  `guestDate` VARCHAR(45) NULL DEFAULT NULL,
  `guestContent` VARCHAR(2048) NULL DEFAULT NULL,
  `guestFlag` TINYINT NULL DEFAULT NULL,
  `guestPass` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`guestNum`));